/**
 * Events
 */
const CREATE_ASSET_FOLDER_EVENT = 'CREATE_ASSET_FOLDER';
const ARCHIVE_ASSET_FOLDER_EVENT = 'ARCHIVE_ASSET_FOLDER';

/**
 * Messages
 */
const FIND_MANY_ASSET_FOLDERS_MESSAGE = 'FIND_MANY_ASSET_FOLDERS';

export { CREATE_ASSET_FOLDER_EVENT, ARCHIVE_ASSET_FOLDER_EVENT, FIND_MANY_ASSET_FOLDERS_MESSAGE };
