/**
 * Events
 */
const UPLOAD_ASSET_EVENT = 'UPLOAD_ASSET';
const ARCHIVE_ASSET_EVENT = 'ARCHIVE_ASSET';

/**
 * Messages
 */
const FIND_MANY_ASSETS_MESSAGE = 'FIND_MANY_ASSETS';

export { UPLOAD_ASSET_EVENT, ARCHIVE_ASSET_EVENT, FIND_MANY_ASSETS_MESSAGE };
