/**
 * Events
 */
const ARCHIVE_ASSET_EVENT = 'ARCHIVE_ASSET';

/**
 * Messages
 */
const FIND_MANY_ASSETS_MESSAGE = 'FIND_MANY_ASSETS';

const MAX_UPLOADED_FILE_SIZE_IN_BYTES = 104857600; // 100 MiB

export { ARCHIVE_ASSET_EVENT, FIND_MANY_ASSETS_MESSAGE, MAX_UPLOADED_FILE_SIZE_IN_BYTES };
