const ASSET_ARCHIVED_EVENT_GLOBAL = 'ASSET_ARCHIVED_EVENT_GLOBAL';
const ASSET_UPLOADED_EVENT_GLOBAL = 'ASSET_UPLOADED_EVENT_GLOBAL';

export { ASSET_ARCHIVED_EVENT_GLOBAL, ASSET_UPLOADED_EVENT_GLOBAL };
