const TEMPLATE_ARCHIVED_EVENT_GLOBAL = 'TEMPLATE_ARCHIVED_EVENT_GLOBAL';
const TEMPLATE_CREATED_EVENT_GLOBAL = 'TEMPLATE_CREATED_EVENT_GLOBAL';
const TEMPLATE_PUBLISHED_EVENT_GLOBAL = 'TEMPLATE_PUBLISHED_EVENT_GLOBAL';
const TEMPLATE_REPLACED_EVENT_GLOBAL = 'TEMPLATE_REPLACED_EVENT_GLOBAL';

export {
  TEMPLATE_ARCHIVED_EVENT_GLOBAL,
  TEMPLATE_CREATED_EVENT_GLOBAL,
  TEMPLATE_PUBLISHED_EVENT_GLOBAL,
  TEMPLATE_REPLACED_EVENT_GLOBAL,
};
