/**
 * Events
 */
const CREATE_TEMPLATE_EVENT = 'CREATE_TEMPLATE';
const ARCHIVE_TEMPLATE_EVENT = 'ARCHIVE_TEMPLATE';
const PUBLISH_TEMPLATE_EVENT = 'PUBLISH_TEMPLATE';
const REPLACE_TEMPLATE_EVENT = 'REPLACE_TEMPLATE';

/**
 * Messages
 */
const FIND_ONE_TEMPLATE_MESSAGE = 'FIND_ONE_TEMPLATE';
const FIND_MANY_TEMPLATES_MESSAGE = 'FIND_MANY_TEMPLATES';

export {
  CREATE_TEMPLATE_EVENT,
  ARCHIVE_TEMPLATE_EVENT,
  PUBLISH_TEMPLATE_EVENT,
  REPLACE_TEMPLATE_EVENT,
  FIND_ONE_TEMPLATE_MESSAGE,
  FIND_MANY_TEMPLATES_MESSAGE,
};
