const ENDPOINT_TEMPLATES_SLUG = 'templates';

/**
 * Command slugs
 */
const CREATE_TEMPLATE_SLUG = 'create';
const ARCHIVE_TEMPLATE_SLUG = 'archive';
const PUBLISH_TEMPLATE__SLUG = 'publish';
const REPLACE_TEMPLATE_SLUG = 'replace';

/**
 * Query slugs
 */
const FIND_ONE_TEMPLATE_SLUG = ':id';

export {
  ENDPOINT_TEMPLATES_SLUG,
  CREATE_TEMPLATE_SLUG,
  ARCHIVE_TEMPLATE_SLUG,
  PUBLISH_TEMPLATE__SLUG,
  REPLACE_TEMPLATE_SLUG,
  FIND_ONE_TEMPLATE_SLUG,
};
