const PAGE_DOMAIN_NAME = 'page';

const PAGE_ARCHIVED_EVENT_TYPE = 'PageArchived';
const PAGE_DRAFT_CREATED_EVENT_TYPE = 'PageDraftCreated';
const PAGE_PUBLISHED_EVENT_TYPE = 'PagePublished';
const PAGE_UNPUBLISHED_EVENT_TYPE = 'PageUnpublished';

const PAGE_ASSET_ELEMENT_VALUE_SETTED_EVENT_TYPE = 'PageAssetElementValueSetted';
const PAGE_DATE_TIME_ELEMENT_VALUE_SETTED_EVENT_TYPE = 'PageDateTimeElementValueSetted';
const PAGE_MULTIPLE_CHOICE_ELEMENT_VALUE_SETTED_EVENT_TYPE = 'PageMultipleChoiceElementValueSetted';
const PAGE_NUMBER_ELEMENT_VALUE_SETTED_EVENT_TYPE = 'PageNumberElementValueSetted';
const PAGE_TEXT_ELEMENT_VALUE_SETTED_EVENT_TYPE = 'PageTextElementValueSetted';

export {
  PAGE_DOMAIN_NAME,
  PAGE_ARCHIVED_EVENT_TYPE,
  PAGE_DRAFT_CREATED_EVENT_TYPE,
  PAGE_PUBLISHED_EVENT_TYPE,
  PAGE_UNPUBLISHED_EVENT_TYPE,
  PAGE_ASSET_ELEMENT_VALUE_SETTED_EVENT_TYPE,
  PAGE_DATE_TIME_ELEMENT_VALUE_SETTED_EVENT_TYPE,
  PAGE_MULTIPLE_CHOICE_ELEMENT_VALUE_SETTED_EVENT_TYPE,
  PAGE_NUMBER_ELEMENT_VALUE_SETTED_EVENT_TYPE,
  PAGE_TEXT_ELEMENT_VALUE_SETTED_EVENT_TYPE,
};
