/**
 * Events
 */
const SET_PAGE_ASSET_ELEMENT_VALUE_EVENT = 'SET_PAGE_ASSET_ELEMENT_VALUE';
const SET_PAGE_DATE_TIME_ELEMENT_VALUE_EVENT = 'SET_PAGE_DATE_TIME_ELEMENT_VALUE';
const SET_PAGE_TEXT_ELEMENT_VALUE_EVENT = 'SET_PAGE_TEXT_ELEMENT_VALUE';
const SET_PAGE_NUMBER_ELEMENT_VALUE_EVENT = 'SET_PAGE_NUMBER_ELEMENT_VALUE';
const SET_PAGE_MULTIPLE_CHOICE_ELEMENT_VALUE_EVENT = 'SET_PAGE_MULTIPLE_CHOICE_ELEMENT_VALUE';

export {
  SET_PAGE_ASSET_ELEMENT_VALUE_EVENT,
  SET_PAGE_DATE_TIME_ELEMENT_VALUE_EVENT,
  SET_PAGE_TEXT_ELEMENT_VALUE_EVENT,
  SET_PAGE_NUMBER_ELEMENT_VALUE_EVENT,
  SET_PAGE_MULTIPLE_CHOICE_ELEMENT_VALUE_EVENT,
};
