const CREATE_PAGE_DRAFT_EVENT = 'CREATE_PAGE_DRAFT';
const ARCHIVE_PAGE_EVENT = 'ARCHIVE_PAGE';
const PUBLISH_PAGE_EVENT = 'PUBLISH_PAGE';
const UNPUBLISH_PAGE_EVENT = 'UNPUBLISH_PAGE';

export { CREATE_PAGE_DRAFT_EVENT, ARCHIVE_PAGE_EVENT, PUBLISH_PAGE_EVENT, UNPUBLISH_PAGE_EVENT };
